language: scala

scala:
  - 2.12.6

notifications:
  email:
    - kexin.xie@salesforce.com

branches:
  only:
    - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION core/assembly
